### ISSUE TITLE
TRABALHO COMPILADORES

### ISSUE THREAD

**Issue by gabriellerosa** [mathiasbrito/CET058#5]
Boa noite professor, gostaria de saber sobre o texto que devemos fazer no trabalho. É pra enviar pro senhor por email ? Escrever e por no git hub (pfv nao kk) ou levar escrito a mao ou impresso ?

**Comment by mathiasbrito** [comment]
Escreve um arquivo REAME.md no diretório da sua solução... GitHub sim! Rsrsrs mas caos tenha problemas me manda um zip com tudo.

**Comment by mathiasbrito** [comment]
Fechando Issue...
