### ISSUE TITLE
Como enviar o projeto

### ISSUE THREAD

**Issue by ellisonguimaraes** [mathiasbrito/CET058#7]
## Professor, bom dia. 

Não tive como levar o projeto e o relatório na aula de hoje. Posso mandar através do email? Se sim, qual o email que posso enviar? Se não, como posso fazer pra te entregar?

Obrigado.

**Comment by mathiasbrito** [comment]
Olá Allison, como falei o relatório deve ser o README do diretório com a solução do projeto.

**Comment by ellisonguimaraes** [comment]
Já está lá. Coloquei o senhor como colaborador do repositório a poucos minutos. Obrigado.

**Comment by mathiasbrito** [comment]
ok.
